config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :chatrooms, only: [:show, :index] do
  resources :messages, only: :create
  end

  get :dashboard, to: 'pages#dashboard'
  get :economies, to: 'pages#economies'

  resource :dashboard, only: [] do
    get :container_graph, to: 'dashboard#container_graph'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.htm
    resources :containers, only: [:index, :update, :show]
    resources :roads, only: [:index, :update, :show]
    resources :road_containers, only: [:update, :show]
    resources :trucks, only: [:index, :show, :update, :create, :new, :destroy, :edit]
end

app/models/truck.rb
class Truck < ApplicationRecord
  belongs_to :city_hall
  has_many :users
  has_many :roads
  has_one_attached :photo
end

app/controllers/trucks_controller.rb
class TrucksController < ApplicationController
	def index
   @trucks = policy_scope(Truck)
	end

	def show
	 @truck = Truck.find(params[:id])
	 authorize @truck
	end

  def edit
    @truck = Truck.find(params[:id])
    authorize @truck
  end

  def update
    @truck = Truck.find(params[:id])
    authorize @truck
    if @truck.update(truck_params)
      redirect_to trucks_path
    else
      render :new
    end
  end

  def new
    @truck = Truck.new
    authorize @truck
  end

  def create
    @truck = Truck.new(truck_params)
    authorize @truck
    # @truck.city_hall = current_user.city_hall
    @truck.city_hall = CityHall.first
    if @truck.save
    redirect_to trucks_path
   else
    render :new
   end
  end

  def destroy
    @truck = Truck.find(params[:id])
    @truck.destroy
    authorize @truck
    redirect_to trucks_path
  end

  private

  def truck_params
    params.require(:truck).permit(:plate_number, :consumption, :kilometers)
  end
end

app/views/trucks/_truckshow.html.erb
<div class="card-product d-flex" style="justify-content: space-between; height: auto;">
  <div class="card-product-infos">
    <p> <%= truck.kilometers %> Km </p>
    <p> <%= truck.consumption %> CO2 </p>
    <p> <%= truck.city_hall.name %> </p>
    <p><%= "team #{count}" %></p>
  </div>
  <% unless truck.photo.key.nil? %>
    <%= cl_image_tag truck.photo.key, size: "150"%>
  <% end %>
</div>

app/views/trucks/edit.html.erb
<div class= "form-truck-div">
  <div class="card-category p-3 d-flex flex-column align-items-center">
    <%= image_tag "garbage-truck.png", size: "70" %>
    <%= simple_form_for(@truck) do |f| %>
    <%= f.input :plate_number, label: "Immatriculation", placeholder: "ex :AB567SK", input_html: {class:"new-truck-input1"} %>
    <%= f.input :kilometers, label: "Kilometrage", placeholder: "ex : 250988",input_html: { class: 'new-truck-input2'} %>
    <%#= f.input :city_hall, label: "Mairie Correspondante", placeholder: "..."%>
    <div class="w-100 d-flex justify-content-center">
      <%=f.submit "Modifier", class: "form-btn-new-truck" %>
    </div>
    <% end %>
  </div>
</div>

app/views/trucks/index.html.erb
<ul>
  <%@trucks.each do |truck| %>
  <div class="card-truck-view p-3">
    <li><span class="registration-ui-truck"><%= truck.plate_number %></span></li>
    <div class="text-center">
      <h2 class="lh-1"> Mairie : <strong><%=truck.city_hall.name%></strong></h2>
      <p class="lh-1"><strong> Kilometers : </strong><%= truck.kilometers %></p>
    </div>
    <div class="btn-notification-actions btn-position">

      <%= link_to edit_truck_path(truck) do %>
        Edit  <i class="fas fa-pencil-alt"></i>
      <% end %>

      <%= link_to truck_path(truck), method: :delete, data: {confirm: "Etes-vous surs?"} do %>
        Delete  <i class="far fa-trash-alt"></i>
      <% end %>
    </div>
  </div>
  <%end%>
  <div class= "d-flex justify-content-center">
    <%= link_to "Ajouter un camion", new_truck_path, class: 'btn-add-truck' %>
  </div>
</ul>

app/views/trucks/new.html.erb
<div class= "container-truck">
  <div class= "form-truck-div">
    <%= image_tag "garbage-truck.png", size: "70" %>
    <%= simple_form_for(@truck) do |f| %>
    <%= f.input :plate_number, label: "Immatriculation", placeholder: "ex :AB567SK", input_html: {class:"new-truck-input1"} %>
    <%= f.input :kilometers, label: "Kilometrage", placeholder: "ex : 250988",input_html: { class: 'new-truck-input2'} %>
    <%#= f.input :city_hall, label: "Mairie Correspondante", placeholder: "..." %>
    <div class="w-100 d-flex justify-content-center">
      <%= f.submit "Ajouter", class: "form-btn-new-truck" %>
    </div>
    <% end %>
  </div>
</div>

app/views/trucks/show.html.erb
<div class="card-product">
  <div class="card-product-infos">
    <p> <%= @truck.kilometers %> Km </p>
    <p> <%= @truck.consumption %> CO2 </p>
    <p> <%= @truck.city_hall.name %> </p>
  </div>
</div>