config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :chatrooms, only: [:show, :index] do
  resources :messages, only: :create
  end

  get :dashboard, to: 'pages#dashboard'
  get :economies, to: 'pages#economies'

  resource :dashboard, only: [] do
    get :container_graph, to: 'dashboard#container_graph'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.htm
    resources :containers, only: [:index, :update, :show]
    resources :roads, only: [:index, :update, :show]
    resources :road_containers, only: [:update, :show]
    resources :trucks, only: [:index, :show, :update, :create, :new, :destroy, :edit]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon <%='new_color' if url_for != '/' %>">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <span id= "logo-police">WAST</span><span id= "logo-police1">RACK</span>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%if url_for == '/'%>
              <%= link_to "Tableau de bord", dashboard_path, class: "nav-link" %>
            <%end%>
          </li>
          <li class="nav-item dropdown">
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%#= link_to "Action", "#", class: "dropdown-item" %>
              <%#= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_sidebar-1.html.erb
<div class="d-flex flex-column flex-shrink-0 p-3 text-white sidetracks" style="width: 280px;">
    <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
	<%# <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg> %>
	<% if @city_hall %>
		<span class="fs-4">Mairie de <%= @city_hall.name %></span>
	<% else %>
	<%# A CHANGER AVEC UN @city_hall SUR TOUTE LES PAGES %>
      <span class="fs-4">Mairie de Megève</span>
	<% end %>
    </a>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
      <li class="nav-item">
		<%= link_to root_path, class:"nav-link #{ 'active' if url_for == root_path}" do %>
		  <i class="fa-solid fa-house"></i>
          Accueil
        <% end %>
      </li>
      <li>
		<%= link_to dashboard_path, class:"nav-link #{ 'active' if url_for == dashboard_path}" do %>
		  <i class="fa-solid fa-gauge-high"></i>
          Tableau de bord
        <% end %>
      </li>
      <li>
		<%= link_to roads_path, class:"nav-link #{ 'active' if url_for == roads_path}" do %>
		  <i class="fa-solid fa-road"></i>
          Itinéraires
        <% end %>
      </li>
      <li>
		<%= link_to trucks_path, class:"nav-link #{ 'active' if url_for == trucks_path}" do %>
		  <i class="fa-solid fa-truck"></i>
          Flotte
        <% end %>
      </li>
      <li>
		<%= link_to economies_path, class:"nav-link #{ 'active' if url_for == economies_path}" do %>
		  <i class="fa-solid fa-euro-sign"></i>
          Economies
        <% end %>
      </li>
    </ul>
    <hr>
    <%# <div class="dropdown"> %>
    <%= link_to dashboard_path, class:"d-flex align-items-center text-white text-decoration-none #{ 'active' if url_for == chatroom_path(1)}" do %>
        <%# <img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2"> %>
       <i class="fa-solid fa-circle-question ms-1" ></i>
      <strong style="margin-left: 10px;"> Chatroom </strong>
      <% end %>
      <%# <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
        <li><a class="dropdown-item" href="#">New project...</a></li>
        <li><a class="dropdown-item" href="#">Settings</a></li>
        <li><a class="dropdown-item" href="#">Profile</a></li>
        <li><hr class="dropdown-divider"></li>
        <li><a class="dropdown-item" href="#">Sign out</a></li>
      </ul> %>
    <%# </div> %>
  </div>