config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :chatrooms, only: [:show, :index] do
  resources :messages, only: :create
  end

  get :dashboard, to: 'pages#dashboard'
  get :economies, to: 'pages#economies'

  resource :dashboard, only: [] do
    get :container_graph, to: 'dashboard#container_graph'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.htm
    resources :containers, only: [:index, :update, :show]
    resources :roads, only: [:index, :update, :show]
    resources :road_containers, only: [:update, :show]
    resources :trucks, only: [:index, :show, :update, :create, :new, :destroy, :edit]
end

app/views/pages/_info_window.html.erb
<%if container.temperature < 50 %>
  <p><%= container.location %></p>
  <p>taux de remplissage:<%= container.filling_level %> %</p>
  <div class="container-photo">
    <%= cl_image_tag container.photo.key, size: "150"%>
    <div class="infos-container">
    <%=link_to "En savoir plus", container_path(container), class: "btn-map-card-dashboard"  %>
    </div>
  </div>
<%else %>
    <div>
      <p><%= container.location %></p>
      <p>Temperature critique <%= container.temperature %> °C</p>
    </div>
    <div class="mb-2">
      <%= cl_image_tag container.photo.key, size: "150"%>
    </div>
    <div>
        <%=link_to "Informer mes employés", chatroom_path(@chatroom), class: "btn-map-card-dashboard"%>
        <%#=Message.new(content: "Quelqu'un à proximité du conteneur situé #{container.location} ?", chatroom_id: @chatroom.id, user_id: current_user.id)%>
    </div>
<%end %>

app/views/pages/dashboard.html.erb
<div class="container-dashboard">
    <div class="welcome-message">
      <h1>Bonjour <%=current_user.first_name%>,</h1>
    </div>
	<div class="cards">

    <div id="mapdiv">
      <div class="card-category p-3" style="width: 100%; height: 100%;">
      	<div class="statistics-menu">
          <div class= "d-flex" id="rec-effect">
            <h5>Carte</h5>
          </div>
          <div>
            <button type="button" class="btn btn-warning"><%= l( Date.today, format: '%d %B') %></button>
          </div>
		    </div>
        <div style="width: 100%; height: 80%;"
            data-controller="mapbox"
            data-mapbox-markers-value="<%= @markers.to_json %>"
            data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>
    </div>

	<div id="infodiv" class="card-category d-flex align-content-center", style="padding: 0px">
			<div class="info-content">
				<section class="statis text-center">
					<div class="info-top-d-flex">
						<div class="info-comp">
							<% if @containers_red_count < 2 %>
								<div class="box bg-success p-3">
							<% elsif @containers_red_count < 4 %>
								<div class="box bg-warning p-3">
							<% else %>
								<div class="box bg-danger p-3">
							<% end %>
								<i class="fa-solid fa-trash"></i>
								<h3><%= @containers_red_count %></h3>
								<p class="lead">Conteneurs pleins depuis + de 2 jours</p>
							</div>
						</div>
						<div class="info-comp">
							<% if @average_fill > 6 %>
								<div class="box bg-success p-3">
							<% elsif @average_fill > 4 %>
								<div class="box bg-warning p-3">
							<% else %>
								<div class="box bg-danger p-3">
							<% end %>
								<i class="fa-solid fa-clock"></i>
									<h3> <%= @average_fill %> j</h3>
								<p class="lead">Temps de remplissage</p>
							</div>
						</div>
					</div>
					<div class="info-bot-d-flex">
						<div class="info-comp">
						<% if @dist_moyenne < 30 %>
							<div class="box bg-success p-3">
						<% elsif @dist_moyenne < 60 %>
							<div class="box bg-warning p-3">
						<% else %>
							<div class="box bg-danger p-3">
						<% end %>
								<i class="fa-solid fa-bus"></i>
								<h3> <%= @dist_moyenne %> km</h3>
								<p class="lead">Distance moyenne par jour</p>
							</div>
						</div>
						<div class="info-comp">
						<%count = 0 %>
						<%@containers.each do |container|%>
						  <%count += 1 if container.temperature > 50%>
						<%end%>
						<%# en dur pour l'instant: %>
							<div class="box bg-danger p-3">
								<i class="fa-solid fa-comment-medical"></i>
								<h3><%=count %></h3>
								<p class="lead">Problèmes en attente</p>
							</div>
						</div>
					</div>
				</section>
			</div>
		</div>
    <div id="container-savings">
      <div class="card-category" id= "statistics-card">
        <div class="statistics-menu">
          <div>
            <h5>Type de déchets</h5>
          </div>
          <div>
            <%= link_to economies_path do %>
              <%# <button type="button" class="btn btn-warning">Voir plus</button> %>
            <% end %>
          </div>
        </div>
        <div><%= pie_chart Container.group(:waste_type).count,colors: ["#6e92d4","#ffb1b1","#FFEDB7","#BEDEBC"], height: "400px", donut: true%></div>
      </div>
    </div>

    <div id="container-savings">
      <div class="card-category" id= "statistics-card">
        <div class="statistics-menu">
          <div>
            <h5>Economies</h5>
          </div>
          <div>
            <%= link_to economies_path do %>
              <button type="button" class="btn btn-warning">Voir plus</button>
            <% end %>
          </div>
        </div>
        <div><%= area_chart Road.group_by_year(:date).average(:kilometers), defer: true, height: "400px", colors: ["#85C883"], ytitle: "km par an"%></div>
      </div>
    </div>
  </div>
</div>

app/views/pages/economies.html.erb
<div class="container">
    <div class="container-stats-economies">
        <div class="container-left-stats">
            <div class="container-mots-explications">
              <h1>Vos economies</h1>
            </div>
            <div class="container-weight-waste-types">
                <section class="statis mt-4 text-center" id= "economies-inline">
                    <div class="container-verre info-top">
                        <div class="info-comp waste_type_width">
                            <div class="box bg-success p-3">
                                <i class="fa-solid fa-wine-bottle"></i>
                                <%count = 0%>
                                <% @containers.each do |container|%>
                                <%count += 1 if container.waste_type == 'verre'%>
                                <%end %>
                                <h3><%= count * 10.5%> T</h3>
                                <p class="lead">VERRE</p>
                            </div>
                        </div>
                    </div>

                    <div class="container-papier info-top">
                        <div class="info-comp waste_type_width">
                            <div class="box bg-danger p-3 paper-color">
                                <i class="fa-solid fa-newspaper"></i>
                                <%count = 0%>
                                <% @containers.each do |container|%>
                                <%count += 1 if container.waste_type == 'papier'%>
                                <%end %>
                                <h3><%= count * 10.5%> T</h3>
                                <p class="lead">PAPIER</p>
                            </div>
                        </div>
                    </div>

                    <div class="container-plastique info-top">
                        <div class="info-comp waste_type_width">
                            <div class="box bg-plastique p-3 plastic-color">
                                <i class="fa-solid fa-bag-shopping"></i>
                                <%count = 0%>
                                <% @containers.each do |container|%>
                                <%count += 1 if container.waste_type == 'plastique'%>
                                <%end %>
                                <h3><%= count * 10.5%> T</h3>
                                <p class="lead">PLASTIQUE</p>
                            </div>
                        </div>
                    </div>

                    <div class="container-reste info-top">
                        <div class="info-comp waste_type_width">
                            <div class="box bg-warning p-3 reste-color">
                                <i class="fa-solid fa-trash"></i>
                                <%count = 0%>
                                <% @containers.each do |container|%>
                                <%count += 1 if container.waste_type == 'reste'%>
                                <%end %>
                                <h3><%= count * 10.5%> T</h3>
                                <p class="lead">AUTRES</p>
                            </div>
                        </div>
                    </div>  
                </section>
            </div>
            <div class="container-savings-km-carbone">
                <div class="savings-carbone">
                    <h5>Trajet quotidien en <mark id="highlight-green">kilomètres</mark></h5>
                    <div><%= area_chart Road.group_by_year(:date).average(:kilometers), defer: true, height: "400px", colors: ["#85C883"]%></div>
                </div>
                <div class="savings-km">
                    <h5>CO2 rejeté en <mark id="highlight-yellow">tonnes</mark></h5>
                    <div><%= area_chart @h, defer: true, height: "400px", colors: ["#eee887"]%></div>
                </div>
            </div>
        </div>
        <div class="container-right-stats">

            <div class="card-about-savings-title">
              <h5>Economies</h5>
            </div>

            <div class="card-about-savings">
              <i class="fa-solid fa-gas-pump"></i>
              <div class="savings-in-numbers">
                <h2>80 L</h2>
              </div>
            </div>

            <div class="card-about-savings">
              <i class="fa-solid fa-money-bill"></i>
              <div class="savings-in-numbers">
                <h2>5000 €</h2>
              </div>
            </div>

            <div class="card-about-savings">
              <i class="fa-solid fa-clock"></i>
              <div class="savings-in-numbers">
                <h2>40h</h2>
              </div>
            </div>

            <div class="card-about-savings">
               <p>CO2</p>
              <div class="savings-in-numbers" id="co2-economies-card">
                 <h2>3T</h2>
              </div>
            </div>
        </div>
    </div>
</div>

app/views/pages/home.html.erb
<div class="landingpage">

  <div class="first-part-text-landing">
    <h1 class="first-part-title-landing" id="opti">Optimisez votre</h1>
    <h1 class="second-part-title-landing">waste management</h1>
    <p>Un itinéraire de collecte optimisé en fonction du taux de <br>remplissage des conteneurs de la ville.</p>
    <%= link_to "Je demande une démo →", "#", class: "btn btn-success btn-landingpage" %>
  </div>
      <%= image_tag('big-rond.png', class: "big-rond-landingpage") %>
      <%= image_tag('iPhone 13 Pro.png', class: "iphone-landingpage") %>
  <div class="second-part-text-landing">
    <div class="advantages-landing-page-title">
      <div>
        <h1 class="first-part-title-landing">Nos avantages</h1>
        <p class= "text-content" >Wastrack vous apporte des nombreux avantages en termes <br>d'organisations et de gain de temps qui passent par des fonctionnalités pensées pour vous.</p>
      </div>
      <div class="icons-landing-page">
        <div class="camembert-div-landing">
          <%= image_tag('camembert.png', class: "first-icon-landing all-icons-landng") %>
          <h5>Analysez les données <br>de votre secteur</h5>
          <p class="text-icons-landing">Des graphiques simples qui permettent une lecture facile.</p>
        </div>
        <div class="finger-div-landing">
          <%= image_tag('finger.png', class: "second-icon-landing all-icons-landng") %>
          <h5>Des outils pensés <br>pour tous</h5>
          <p class="text-icons-landing">À disposition une application pour les ramasseurs et un site pour les mairies</p>
        </div>
        <div class="protect-div-landing">
          <%= image_tag('protect.png', class: "third-icon-landing all-icons-landng") %>
          <h5>Vos données sont <br>protégées</h5>
          <p class="text-icons-landing">Grâce à notre politique vos données sont sécurisées.</p>
        </div>
        <div class="graph-div-landing">
          <%= image_tag('graph.png', class: "fourth-icon-landing all-icons-landng") %>
          <h5>Retrouvez tout d'un <br>simple coup d'oeil</h5>
          <p class="text-icons-landing">Grâce à un site organisé trouvez toutes les données simplement.</p>
        </div>
      </div>
    </div>
  </div>

  <div class="third-part-text-landing">
    <div class= "third-part-flex">

      <ol class="gradient-list">
        <h1 class="third-part-title-landing">Une application <br>mobile pour les <br>collecteurs</h1>
       <li>
         <%#= image_tag('Line 1.png', class: "landing-line-1") %>
          Commencez votre journée facilement
       </li>
       <li>
         <%#= image_tag('Line 1.png', class: "landing-line-2 content-landing-third") %>
          la route optimisée par l’application
       </li>
       <li>
         <%#= image_tag('Line 1.png', class: "landing-line-3") %>
          Signalez tout problème
       </li>
    </ol>

    <%= image_tag('3-phone.png', class: "three-phone-landingpage") %>
  </div>
  </div>

  <div class="footer">
    <div class="footer-links">
      <a href="#"><i class="fab fa-github"></i></a>
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-linkedin"></i></a>
    </div>
    <div class="footer-copyright">
      Conditions Générales  •  Confidentialité  •  Contact
    </div>
  </div>
</div>